pipeline{
    agent any 
    stages{
        stage('Example'){
            input{
                message "Should we continue?"
                ok "Yes, we should"
                submiter "admin"
                parameters{
                    string(name:'PERSON',defalutValue:'Mr Jenkins',description:'Who should I say hello to?')
                }
            }
            steps{
                echo "Hello, ${PERSON}, nice to meet you."
            }
        }
    }
}