pipeline{
    agent any
    triggers{
        upstream(
            upstreamProjects:'pipelines',threshold: hudson.model.Result.SUCCESS
        )
    }
    stages{
        stage('Test'){
            steps{
                echo 'rodando ...'
            }
        }
    }
}