pipeline{
    agent any 
    stages{
        stage('Test'){
            steps{



                script{
                    def server = Artifactory.newServer 'http://142.93.254.193:8081/artifactory', 'admin', 'password'
                    /*def downloadSpec = """ 
                        {
                            "files" : [
                                {
                                    "pattern" : "libs-release-local/br/com/m2msolutions/copiloto/copiloto-client/1.1.0/copiloto-client-1.1.0.jar", 
                                    "target" : "binario/"
                                }
                            ]
                        }
                    
                    """

                    server.download(downloadSpec); 

                    println "binario baixado"*/


                    def uploadSpec = """ {

                        "files" : [
                            {
                                "pattern" : "m2m-worker-bilhetagem-1.4.2.jar", 
                                "target" : "libs-snapshot-local/br/com/m2msolutions/workerbilhetagem/m2m-worker-bilhetagem-1.4.2.jar"
                            }
                        ]    
                    }
                        
                    """

                    def buildInfo = server.upload(uploadSpec)
                    server.publishBuildInfo(buildInfo); 
                }

                sh "pwd"
                sh "ls"
                
            }
        }
    }
}