pipeline{
    agent any 
    stages{
        stage('Test'){
            script{
                def server = Artifactory.newServer 'http://142.93.254.193:8081/artifactory', 'admin', 'password'
                println server.properties 
            }
        }
    }
}